@startuml

title プレイヤーの手持ちカードの文字列表記を問い合わせる

''left to right direction

actor PHPシステム

package "Porker" {
    boundary Playerエンティティ
    control getNotation
}

package "Trump" {
    usecase カード一枚の文字列表記を返す
}


PHPシステム --> Playerエンティティ
Playerエンティティ --> getNotation
getNotation --> カード一枚の文字列表記を返す


@enduml