@startuml

title ユーザがシステムを操作

left to right direction

actor ユーザ

package "PHPシステム" {
    usecase (システムログイン)
    usecase (Pokerゲーム開始)
    usecase (手札交換をスキップ)
    usecase (いらないCardを１～５枚捨てる)
    usecase (手札の比較により勝敗を判定)
    usecase (総合成績発表)
    usecase (システムログアウト)

    package "Poker" {
        usecase (手札すべての文字列表記を取得)
    }

    package "Trump" {
        usecase (カード一枚の文字列表記を返す)
    }
}

'' ユーザ直下の位置関係だけを制御する
ユーザ -[hidden]d- PHPシステム

ユーザ --> (システムログイン)
ユーザ --> (Pokerゲーム開始)
ユーザ --> (いらないCardを１～５枚捨てる)
ユーザ --> (手札交換をスキップ)
ユーザ --> (手札の比較により勝敗を判定)
ユーザ --> (総合成績発表)
ユーザ --> (システムログアウト)

'' PHPシステム内部の第一層について、右(上)から順に位置関係を制御する
(システムログイン) -[hidden]l- (Pokerゲーム開始)
(Pokerゲーム開始) -[hidden]l- (いらないCardを１～５枚捨てる)
(いらないCardを１～５枚捨てる) -[hidden]l- (手札交換をスキップ)
(手札交換をスキップ) -[hidden]l- (手札の比較により勝敗を判定)
(手札の比較により勝敗を判定) -[hidden]l- (総合成績発表)
(総合成績発表) -[hidden]l- (システムログアウト)

'' PHPシステム内部の第一層と第二層との関係性
(いらないCardを１～５枚捨てる) --> (手札すべての文字列表記を取得)
(手札交換をスキップ) --> (手札すべての文字列表記を取得)
(手札の比較により勝敗を判定) --> (手札すべての文字列表記を取得)

'' PHPシステム内部の第二層内での関係性
(手札すべての文字列表記を取得) -l-> (カード一枚の文字列表記を返す)



@enduml